version: '2'

services:

  mysql-server:
    image: mysql:5.7
    # for rpi
    #image: hypriot/rpi-mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#      MYSQL_USER: myweb
#      MYSQL_PASSWORD: secret
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      app_net:

  apache-server:
    build:
      context: ./docker/apache
#    image: apps4net/laravel-apache:1.0
#    image: apache
    ports:
      - ${APP_PORT}
#      - "443:443"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: always
    volumes:
      - ./www:/var/www/html
    links:
      - mysql-server
    networks:
      app_net: 
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-server
      PHP_UPLOAD_MAX_FILESIZE: 67108864
    networks:
      app_net:
    
networks:
  app_net:
